apiVersion: v1
kind: Service
metadata:
  name: octoprint-nodeport
  namespace: default
spec:
  type: NodePort
  selector:
    app: octoprint
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30001
